[package]
name = "concept"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4.20"
houtamelo_utils = "1.2"
yarn_spire_codegen = { path = "../codegen"}
thiserror = "1.0"
enum_dispatch = "0.3"